# Generated by Django 4.2.6 on 2023-10-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='due_date',
            field=models.DateField(),
        ),
    ]
