# Generated by Django 4.2.6 on 2023-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_created_time_alter_notes_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
