# Generated by Django 4.2.6 on 2023-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notes_is_finished_alter_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='due_date',
            field=models.DateField(),
        ),
    ]
